### ISSUE TITLE
It is not working for me :(

### ISSUE THREAD

**Issue by Grv90** [isrmicha/react-native-disqus#3]
just shows the spinner and goes away, can u help please

**Comment by isrmicha** [comment]
What version of React Native are you using ?

Have you follow the example ?

**Comment by Tautorn** [comment]
Not working for me too.

`Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.`

**Comment by Tautorn** [comment]
Necessary install   "react-native-autoheight-webview" and "react-native-webview": "^7.4.3".

**Comment by zooptradenz** [comment]
@Tautorn is it working for you now wit this webview ?

**Comment by isrmicha** [comment]
update readme
use  "react-native-webview": "^7.4.3"

**Comment by Sahejmaharjan1** [comment]
Tried  "react-native-webview": "^7.4.3" still didn't work..
I get error saying 
```
error: index.js: Transformer is not a constructor
```
